// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC6EByMjGRQxFCUAI87V9kisHH9eFZZXM',
    appId: '1:4319556033:web:ca23d508b795b7d9067f40',
    messagingSenderId: '4319556033',
    projectId: 'stillfeed-1',
    authDomain: 'stillfeed-1.firebaseapp.com',
    storageBucket: 'stillfeed-1.firebasestorage.app',
    measurementId: 'G-HTMFNRKW11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcq5k5VUUFt8DZlQ3yZA2ojucAF1Dd6zM',
    appId: '1:4319556033:android:0350879a418f626e067f40',
    messagingSenderId: '4319556033',
    projectId: 'stillfeed-1',
    storageBucket: 'stillfeed-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQIkPlaiPMyCIujGl799mdjmxIBPA9F4',
    appId: '1:4319556033:ios:159ee2c20f13b186067f40',
    messagingSenderId: '4319556033',
    projectId: 'stillfeed-1',
    storageBucket: 'stillfeed-1.firebasestorage.app',
    iosBundleId: 'com.example.buildersolveJsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQIkPlaiPMyCIujGl799mdjmxIBPA9F4',
    appId: '1:4319556033:ios:159ee2c20f13b186067f40',
    messagingSenderId: '4319556033',
    projectId: 'stillfeed-1',
    storageBucket: 'stillfeed-1.firebasestorage.app',
    iosBundleId: 'com.example.buildersolveJsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC6EByMjGRQxFCUAI87V9kisHH9eFZZXM',
    appId: '1:4319556033:web:f26cf858052d5599067f40',
    messagingSenderId: '4319556033',
    projectId: 'stillfeed-1',
    authDomain: 'stillfeed-1.firebaseapp.com',
    storageBucket: 'stillfeed-1.firebasestorage.app',
    measurementId: 'G-WT0RY2CX60',
  );
}
